export const issuesResponse = [
    {
      "url": "https://api.github.com/repos/facebook/react/issues/19828",
      "repository_url": "https://api.github.com/repos/facebook/react",
      "labels_url": "https://api.github.com/repos/facebook/react/issues/19828/labels{/name}",
      "comments_url": "https://api.github.com/repos/facebook/react/issues/19828/comments",
      "events_url": "https://api.github.com/repos/facebook/react/issues/19828/events",
      "html_url": "https://github.com/facebook/react/issues/19828",
      "id": 700679981,
      "node_id": "MDU6SXNzdWU3MDA2Nzk5ODE=",
      "number": 19828,
      "title": "Bug: A menu item in tutorial doesn't get highlighted on click",
      "user": {
        "login": "izdwuut",
        "id": 33417130,
        "node_id": "MDQ6VXNlcjMzNDE3MTMw",
        "avatar_url": "https://avatars3.githubusercontent.com/u/33417130?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/izdwuut",
        "html_url": "https://github.com/izdwuut",
        "followers_url": "https://api.github.com/users/izdwuut/followers",
        "following_url": "https://api.github.com/users/izdwuut/following{/other_user}",
        "gists_url": "https://api.github.com/users/izdwuut/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/izdwuut/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/izdwuut/subscriptions",
        "organizations_url": "https://api.github.com/users/izdwuut/orgs",
        "repos_url": "https://api.github.com/users/izdwuut/repos",
        "events_url": "https://api.github.com/users/izdwuut/events{/privacy}",
        "received_events_url": "https://api.github.com/users/izdwuut/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 155984160,
          "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
          "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
          "name": "Status: Unconfirmed",
          "color": "d4c5f9",
          "default": false,
          "description": "A potential issue that we haven't yet confirmed as a bug"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [
  
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-09-14T00:25:59Z",
      "updated_at": "2020-09-14T01:07:14Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "<!--\r\n  Please provide a clear and concise description of what the bug is. Include\r\n  screenshots if needed. Please test using the latest version of the relevant\r\n  React packages to make sure your issue has not already been fixed.\r\n-->\r\nHi!\r\n\r\nI've been working my way through your marvelous [tutorial](https://reactjs.org/tutorial/tutorial.html) when I've noticed that once you click on `Overview > Inspecting the Starter Code` in menu, the element doesn't get highlighted. It's because you use `<h3 id=\"inspecting-the-starter-code\">...</h3>` instead of `<h2 id=\"inspecting-the-starter-code\">...</h2>` in your markup. This should be a subheader, not header.\r\n\r\nReact version: Doesn't apply.\r\nBrowser: Firefox Developer Edition 81.0b9 (64-bit).\r\n\r\n## Steps To Reproduce\r\n\r\n1. Go to https://reactjs.org/tutorial/tutorial.html.\r\n2. Click on `Overview > Inspecting the Starter Code` menu item.\r\n\r\n\r\n\r\n<!--\r\n  Your bug will get fixed much faster if we can run your code and it doesn't\r\n  have dependencies other than React. Issues without reproduction steps or\r\n  code examples may be immediately closed as not actionable.\r\n-->\r\n\r\nLink to code example: doesn't apply.\r\n\r\n<!--\r\n  Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a\r\n  repository on GitHub, or provide a minimal code example that reproduces the\r\n  problem. You may provide a screenshot of the application if you think it is\r\n  relevant to your bug report. Here are some tips for providing a minimal\r\n  example: https://stackoverflow.com/help/mcve.\r\n-->\r\n\r\n## The current behavior\r\nThe `Overview > Inspecting the Starter Code` menu element doesn't get highlighted on click.\r\n\r\n## The expected behavior\r\nThe `Overview > Inspecting the Starter Code` element should get highlighted on click.",
      "performed_via_github_app": null
    },
    {
      "url": "https://api.github.com/repos/facebook/react/issues/19827",
      "repository_url": "https://api.github.com/repos/facebook/react",
      "labels_url": "https://api.github.com/repos/facebook/react/issues/19827/labels{/name}",
      "comments_url": "https://api.github.com/repos/facebook/react/issues/19827/comments",
      "events_url": "https://api.github.com/repos/facebook/react/issues/19827/events",
      "html_url": "https://github.com/facebook/react/pull/19827",
      "id": 700643819,
      "node_id": "MDExOlB1bGxSZXF1ZXN0NDg2MjM3MTI3",
      "number": 19827,
      "title": "DevTools: Improve browser extension iframe support",
      "user": {
        "login": "omarsy",
        "id": 15034695,
        "node_id": "MDQ6VXNlcjE1MDM0Njk1",
        "avatar_url": "https://avatars0.githubusercontent.com/u/15034695?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/omarsy",
        "html_url": "https://github.com/omarsy",
        "followers_url": "https://api.github.com/users/omarsy/followers",
        "following_url": "https://api.github.com/users/omarsy/following{/other_user}",
        "gists_url": "https://api.github.com/users/omarsy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/omarsy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/omarsy/subscriptions",
        "organizations_url": "https://api.github.com/users/omarsy/orgs",
        "repos_url": "https://api.github.com/users/omarsy/repos",
        "events_url": "https://api.github.com/users/omarsy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/omarsy/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 196858374,
          "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
          "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
          "name": "CLA Signed",
          "color": "e7e7e7",
          "default": false,
          "description": null
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [
  
      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-09-13T20:41:02Z",
      "updated_at": "2020-09-13T21:29:15Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/19827",
        "html_url": "https://github.com/facebook/react/pull/19827",
        "diff_url": "https://github.com/facebook/react/pull/19827.diff",
        "patch_url": "https://github.com/facebook/react/pull/19827.patch"
      },
      "body": "<!--\r\n  Thanks for submitting a pull request!\r\n  We appreciate you spending the time to work on these changes. Please provide enough information so that others can review your pull request. The three fields below are mandatory.\r\n\r\n  Before submitting a pull request, please make sure the following is done:\r\n\r\n  1. Fork [the repository](https://github.com/facebook/react) and create your branch from `master`.\r\n  2. Run `yarn` in the repository root.\r\n  3. If you've fixed a bug or added code that should be tested, add tests!\r\n  4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.\r\n  5. Run `yarn test-prod` to test in the production environment. It supports the same options as `yarn test`.\r\n  6. If you need a debugger, run `yarn debug-test --watch TestName`, open `chrome://inspect`, and press \"Inspect\".\r\n  7. Format your code with [prettier](https://github.com/prettier/prettier) (`yarn prettier`).\r\n  8. Make sure your code lints (`yarn lint`). Tip: `yarn linc` to only check changed files.\r\n  9. Run the [Flow](https://flowtype.org/) type checks (`yarn flow`).\r\n  10. If you haven't already, complete the CLA.\r\n\r\n  Learn more about contributing: https://reactjs.org/docs/how-to-contribute.html\r\n-->\r\n\r\n## Summary\r\nThis pull requests is intended to improve iframe support for devtools browser extensions(#18945), without add a code to  pass the hook through from the parent.\r\n\r\n![image](https://user-images.githubusercontent.com/15034695/93028132-28a57e00-f612-11ea-8e35-4749a2b2d7bc.png)\r\n\r\n<!-- Explain the **motivation** for making this change. What existing problem does the pull request solve? -->\r\n\r\n## Test Plan\r\n\r\n<!-- Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes the user interface. -->\r\n",
      "performed_via_github_app": null
    },
    {
      "url": "https://api.github.com/repos/facebook/react/issues/19825",
      "repository_url": "https://api.github.com/repos/facebook/react",
      "labels_url": "https://api.github.com/repos/facebook/react/issues/19825/labels{/name}",
      "comments_url": "https://api.github.com/repos/facebook/react/issues/19825/comments",
      "events_url": "https://api.github.com/repos/facebook/react/issues/19825/events",
      "html_url": "https://github.com/facebook/react/pull/19825",
      "id": 700511107,
      "node_id": "MDExOlB1bGxSZXF1ZXN0NDg2MTM5MjQy",
      "number": 19825,
      "title": "Updates to grammar, formatting of README file ",
      "user": {
        "login": "thejessicafelts",
        "id": 10212524,
        "node_id": "MDQ6VXNlcjEwMjEyNTI0",
        "avatar_url": "https://avatars0.githubusercontent.com/u/10212524?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/thejessicafelts",
        "html_url": "https://github.com/thejessicafelts",
        "followers_url": "https://api.github.com/users/thejessicafelts/followers",
        "following_url": "https://api.github.com/users/thejessicafelts/following{/other_user}",
        "gists_url": "https://api.github.com/users/thejessicafelts/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/thejessicafelts/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/thejessicafelts/subscriptions",
        "organizations_url": "https://api.github.com/users/thejessicafelts/orgs",
        "repos_url": "https://api.github.com/users/thejessicafelts/repos",
        "events_url": "https://api.github.com/users/thejessicafelts/events{/privacy}",
        "received_events_url": "https://api.github.com/users/thejessicafelts/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 196858374,
          "node_id": "MDU6TGFiZWwxOTY4NTgzNzQ=",
          "url": "https://api.github.com/repos/facebook/react/labels/CLA%20Signed",
          "name": "CLA Signed",
          "color": "e7e7e7",
          "default": false,
          "description": null
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [
  
      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-09-13T06:45:30Z",
      "updated_at": "2020-09-13T14:11:37Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "pull_request": {
        "url": "https://api.github.com/repos/facebook/react/pulls/19825",
        "html_url": "https://github.com/facebook/react/pull/19825",
        "diff_url": "https://github.com/facebook/react/pull/19825.diff",
        "patch_url": "https://github.com/facebook/react/pull/19825.patch"
      },
      "body": "Updates to grammar and formatting of the README file.\r\n\r\n## Summary\r\n\r\nWhen reading through the README.md file, I thought some changes could be made to make the file easier to read, and more grammatically correct.\r\n\r\n## Test Plan\r\n\r\nN/A - As this is simply a copy update to a .md file, no test plan was created or needed.\r\n\r\n## CLA\r\n\r\nThe CLA has been completed and signed.\r\n",
      "performed_via_github_app": null
    },
    {
      "url": "https://api.github.com/repos/facebook/react/issues/19732",
      "repository_url": "https://api.github.com/repos/facebook/react",
      "labels_url": "https://api.github.com/repos/facebook/react/issues/19732/labels{/name}",
      "comments_url": "https://api.github.com/repos/facebook/react/issues/19732/comments",
      "events_url": "https://api.github.com/repos/facebook/react/issues/19732/events",
      "html_url": "https://github.com/facebook/react/issues/19732",
      "id": 689604207,
      "node_id": "MDU6SXNzdWU2ODk2MDQyMDc=",
      "number": 19732,
      "title": "Bug: React DevTools 'Why did this component render?' incorrectly reports 'The parent component rendered'",
      "user": {
        "login": "bgirard",
        "id": 793565,
        "node_id": "MDQ6VXNlcjc5MzU2NQ==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/793565?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bgirard",
        "html_url": "https://github.com/bgirard",
        "followers_url": "https://api.github.com/users/bgirard/followers",
        "following_url": "https://api.github.com/users/bgirard/following{/other_user}",
        "gists_url": "https://api.github.com/users/bgirard/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/bgirard/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/bgirard/subscriptions",
        "organizations_url": "https://api.github.com/users/bgirard/orgs",
        "repos_url": "https://api.github.com/users/bgirard/repos",
        "events_url": "https://api.github.com/users/bgirard/events{/privacy}",
        "received_events_url": "https://api.github.com/users/bgirard/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 710573595,
          "node_id": "MDU6TGFiZWw3MTA1NzM1OTU=",
          "url": "https://api.github.com/repos/facebook/react/labels/Component:%20Developer%20Tools",
          "name": "Component: Developer Tools",
          "color": "fbca04",
          "default": false,
          "description": null
        },
        {
          "id": 155984160,
          "node_id": "MDU6TGFiZWwxNTU5ODQxNjA=",
          "url": "https://api.github.com/repos/facebook/react/labels/Status:%20Unconfirmed",
          "name": "Status: Unconfirmed",
          "color": "d4c5f9",
          "default": false,
          "description": "A potential issue that we haven't yet confirmed as a bug"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [
  
      ],
      "milestone": null,
      "comments": 4,
      "created_at": "2020-08-31T23:15:59Z",
      "updated_at": "2020-09-03T12:33:50Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "React Devtools shows why a component has re-render but sometimes it says 'The parent component rendered' when it just doesn't know. Ideally we would split out these two scenario, otherwise the string should highlight the uncertainty. Me and another Jimmy both went debugging the wrong thing and I lost time assuming the message was correct.\r\n\r\nReact version: React DevTools 4.8.2\r\n\r\n## Steps To Reproduce\r\n\r\nI believe this bug happens when there's a context changing but I'm not positive.",
      "performed_via_github_app": null
    },
    {
      "url": "https://api.github.com/repos/facebook/react/issues/19731",
      "repository_url": "https://api.github.com/repos/facebook/react",
      "labels_url": "https://api.github.com/repos/facebook/react/issues/19731/labels{/name}",
      "comments_url": "https://api.github.com/repos/facebook/react/issues/19731/comments",
      "events_url": "https://api.github.com/repos/facebook/react/issues/19731/events",
      "html_url": "https://github.com/facebook/react/issues/19731",
      "id": 689421552,
      "node_id": "MDU6SXNzdWU2ODk0MjE1NTI=",
      "number": 19731,
      "title": "Craft a demo profile for the scheduling profiler",
      "user": {
        "login": "kartikcho",
        "id": 48270786,
        "node_id": "MDQ6VXNlcjQ4MjcwNzg2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/48270786?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/kartikcho",
        "html_url": "https://github.com/kartikcho",
        "followers_url": "https://api.github.com/users/kartikcho/followers",
        "following_url": "https://api.github.com/users/kartikcho/following{/other_user}",
        "gists_url": "https://api.github.com/users/kartikcho/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/kartikcho/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kartikcho/subscriptions",
        "organizations_url": "https://api.github.com/users/kartikcho/orgs",
        "repos_url": "https://api.github.com/users/kartikcho/repos",
        "events_url": "https://api.github.com/users/kartikcho/events{/privacy}",
        "received_events_url": "https://api.github.com/users/kartikcho/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 2281766624,
          "node_id": "MDU6TGFiZWwyMjgxNzY2NjI0",
          "url": "https://api.github.com/repos/facebook/react/labels/Component:%20Scheduling%20Profiler",
          "name": "Component: Scheduling Profiler",
          "color": "1dc3d6",
          "default": false,
          "description": ""
        }
      ],
      "state": "closed",
      "locked": false,
      "assignee": null,
      "assignees": [
  
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-08-31T18:53:34Z",
      "updated_at": "2020-08-31T20:42:36Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "We should create a custom demo profile to show the various performance 'patterns' observed in the scheduling profiler.\r\n\r\n**cc: @bvaughn @taneliang**",
      "performed_via_github_app": null
    }
];